version: '3.1'
services:
  db:
    image: alexanderfefelov/postgrespro-1c
    restart: always
    ports:
      - "5432:5432"
    volumes: 
     - ./DATA/pgdata:/data
     - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: 123qweRTY


